### ISSUE TITLE
Installer stops after choosing language and installing deps

### ISSUE THREAD

**Issue by MiMillieuh** [cryinkfly/SOLIDWORKS-for-Linux#28]
Hello, I've tries to install this since one week and I noticed that the installer is completely broken on my system (Fedora 37 workstation)

Here some of my issues : 

if i launch it without any modifications : 

`[mimillie@fedora stable-branch]$ sh solidworks-install.sh`
`solidworks-install.sh: ligne 63: « check-requirement » : identifiant non valable`

If I modify it to remove some steps, every function has an non valid identifient.

and if I can reach the language selection, it will just prompt it and then install deps and stop the installer (the script) without any exit code.

**Comment by Duedot43** [comment]
From what I can read of the error SH might not like the function names? If you can try to remove the - from all the function names it may just be throwing a fit trying to parse it because if you selected languages the 'language' function appears to be fine I'll take a look at it when I'm home in the meantime could you send your SH version number?

**Comment by MiMillieuh** [comment]
Thanks for your reply

I can confirm that I don't have these issue anymore, however now language is hanging on just after I choose one.

no output just nothing.

here the "fixed" script if it can be helpful.
[solidworks-install.zip](https://github.com/cryinkfly/SOLIDWORKS-for-Linux/files/10251829/solidworks-install.zip)

**Comment by cryinkfly** [comment]
@MiMillieuh I have add your changed code. :+1:

**Comment by FoxxMD** [comment]
Hello I am still seeing "hanging after language select" with the latest stable installer
